<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Java&amp;#8482;: A Beginner&amp;#8217;s Guide Sixth Edition</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link href="stylesheet.css" rel="stylesheet" type="text/css"/>
<link href="page_styles.css" rel="stylesheet" type="text/css"/>
</head>
  <body class="calibre">
<div id="filepos764315" class="calibre29"><span><img alt="image" src="images/00003.jpg" class="calibre30"/></span></div><div class="calibre11"> </div>
<div class="calibre31"><span class="calibre2"><span><big class="calibre3"><big class="calibre4"><big class="calibre5"><big class="calibre6"><big class="calibre32"><big class="calibre4">Chapter 9</big></big></big></big></big></big></span></span></div>
<div class="calibre9"><span class="calibre2"><span>Exception Handling</span></span></div><div class="calibre33"> </div>
<div class="calibre1"><span class="calibre10"><span><span class="bold1">Key Skills &amp; Concepts</span></span></span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Know the exception hierarchy</span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Use <span class="bold1">try</span> and <span class="bold1">catch</span></span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Understand the effects of an uncaught exception</span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Use multiple <span class="bold1">catch</span> statements</span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Catch subclass exceptions</span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Nest <span class="bold1">try</span> blocks</span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Throw an exception</span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Know the members of <span class="bold1">Throwable</span></span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Use <span class="bold1">finally</span></span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Use <span class="bold1">throws</span></span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Know Java’s built-in exceptions</span></div>
<div class="calibre26"><span><img alt="image" src="images/00002.jpg" class="calibre25"/>   Create custom exception classes</span></div>
<div class="calibre1"><span><img alt="image" src="images/00004.jpg" class="calibre34"/></span></div><div class="calibre18"> </div>
<div class="calibre12"><span><span><span class="calibre2"><span class="bold1">T</span></span></span>his chapter discusses exception handling. An exception is an error that occurs at run time. Using Java’s exception handling subsystem you can, in a structured and controlled manner, handle run-time errors. Although most modern programming languages offer some form of exception handling, Java’s support for it is both easy-to-use and flexible.</span></div>
<div class="calibre23"><span>A principal advantage of exception handling is that it automates much of the error handling code that previously had to be entered “by hand” into any large program. For example, in some older computer languages, error codes are returned when a method fails, and these values must be checked manually, each time the method is called. This approach is both tedious and error-prone. Exception handling streamlines error handling by allowing your program to define a block of code, called an <span class="italic">exception handler</span>, that is executed automatically when an error occurs. It is not necessary to manually check the success or failure of each specific operation or method call. If an error occurs, it will be processed by the exception handler.</span></div>
<div class="calibre23"><span>Another reason that exception handling is important is that Java defines standard exceptions for common program errors, such as divide-by-zero or file-not-found. To respond to these errors, your program must watch for and handle these exceptions. Also, Java’s API library makes extensive use of exceptions.</span></div>
<div class="calibre23"><span>In the final analysis, to be a successful Java programmer means that you are fully capable of navigating Java’s exception handling subsystem.</span></div>
<div id="filepos769228" class="calibre1"><span class="calibre10"><span><span class="bold1">The Exception Hierarchy</span></span></span></div>
<div class="calibre12"><span>In Java, all exceptions are represented by classes. All exception classes are derived from a class called <span class="bold1">Throwable</span>. Thus, when an exception occurs in a program, an object of some type of exception class is generated. There are two direct subclasses of <span class="bold1">Throwable</span>: <span class="bold1">Exception</span> and <span class="bold1">Error</span>. Exceptions of type <span class="bold1">Error</span> are related to errors that occur in the Java virtual machine itself, and not in your program. These types of exceptions are beyond your control, and your program will not usually deal with them. Thus, these types of exceptions are not described here.</span></div>
<div class="calibre23"><span>Errors that result from program activity are represented by subclasses of <span class="bold1">Exception</span>. For example, divide-by-zero, array boundary, and file errors fall into this category. In general, your program should handle exceptions of these types. An important subclass of <span class="bold1">Exception</span> is <span class="bold1">RuntimeException</span>, which is used to represent various common types of run-time errors.</span></div>
<div id="filepos770467" class="calibre1"><span class="calibre10"><span><span class="bold1">Exception Handling Fundamentals</span></span></span></div>
<div class="calibre12"><span>Java exception handling is managed via five keywords: <span class="bold1">try</span>, <span class="bold1">catch</span>, <span class="bold1">throw</span>, <span class="bold1">throws</span>, and <span class="bold1">finally</span>. They form an interrelated subsystem in which the use of one implies the use of another. Throughout the course of this chapter, each keyword is examined in detail. However, it is useful at the outset to have a general understanding of the role each plays in exception handling. Briefly, here is how they work.</span></div>
<div class="calibre23"><span>Program statements that you want to monitor for exceptions are contained within a <span class="bold1">try</span> block. If an exception occurs within the <span class="bold1">try</span> block, it is <span class="italic">thrown</span>. Your code can catch this exception using <span class="bold1">catch</span> and handle it in some rational manner. System-generated exceptions are automatically thrown by the Java run-time system. To manually throw an exception, use the keyword <span class="bold1">throw</span>. In some cases, an exception that is thrown out of a method must be specified as such by a <span class="bold1">throws</span> clause. Any code that absolutely must be executed upon exiting from a <span class="bold1">try</span> block is put in a <span class="bold1">finally</span> block.</span></div>
<div class="calibre35"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div>
<div class="calibre9"><span class="calibre10"><span><span class="bold1">Ask the Expert</span></span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">Q</span></span>:   Just to be sure, could you review the conditions that cause an exception to be generated?</span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">A</span></span>:</span>   Exceptions are generated in three different ways. First, the Java Virtual Machine can generate an exception in response to some internal error which is beyond your control. Normally, your program won’t handle these types of exceptions. Second, standard exceptions, such as those corresponding to divide-by-zero or array index out-of-bounds, are generated by errors in program code. You need to handle these exceptions. Third, you can manually generate an exception by using the <span class="bold1">throw</span> statement. No matter how an exception is generated, it is handled in the same way.</span></div>
<div class="calibre36"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div><div class="calibre18"> </div>
<div id="filepos773159" class="calibre9"><span class="calibre10"><span><span class="bold1">Using try and catch</span></span></span></div>
<div class="calibre12"><span>At the core of exception handling are <span class="bold1">try</span> and <span class="bold1">catch</span>. These keywords work together; you can’t have a <span class="bold1">catch</span> without a <span class="bold1">try</span>. Here is the general form of the <span class="bold1">try</span>/<span class="bold1">catch</span> exception handling blocks:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00580.jpg" class="calibre595"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>Here, <span class="italic">ExcepType</span> is the type of exception that has occurred. When an exception is thrown, it is caught by its corresponding <span class="bold1">catch</span> statement, which then processes the exception. As the general form shows, there can be more than one <span class="bold1">catch</span> statement associated with a <span class="bold1">try</span>. The type of the exception determines which <span class="bold1">catch</span> statement is executed. That is, if the exception type specified by a <span class="bold1">catch</span> statement matches that of the exception, then that <span class="bold1">catch</span> statement is executed (and all others are bypassed). When an exception is caught, <span class="italic">exOb</span> will receive its value.</span></div>
<div class="calibre23"><span>Here is an important point: If no exception is thrown, then a <span class="bold1">try</span> block ends normally, and all of its <span class="bold1">catch</span> statements are bypassed. Execution resumes with the first statement following the last <span class="bold1">catch</span>. Thus, <span class="bold1">catch</span> statements are executed only if an exception is thrown.</span></div>
<div class="calibre44"><span class="calibre10"><span><span class="bold1"><span class="italic">NOTE</span></span></span></span></div>
<div class="calibre9"><span><img alt="image" src="images/00006.jpg" class="calibre45"/></span></div>
<div class="calibre9"><span>Beginning with JDK 7, there is another form of the <span class="bold1">try</span> statement that supports <span class="italic">automatic resource management</span>. This form of <span class="bold1">try</span> is called <span class="italic"><span class="bold1">try</span>-with-resources</span>. It is described in <a href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_017.html#filepos823752">Chapter 10</a>, in the context of managing I/O streams (such as those connected to a file) because streams are some of the most commonly used resources.</span></div><div class="calibre11"> </div>
<div id="filepos775476" class="calibre1"><span class="calibre10"><span><span class="bold1">A Simple Exception Example</span></span></span></div>
<div class="calibre12"><span>Here is a simple example that illustrates how to watch for and catch an exception. As you know, it is an error to attempt to index an array beyond its boundaries. When this occurs, the JVM throws an <span class="bold1">ArrayIndexOutOfBoundsException</span>. The following program purposely generates such an exception and then catches it:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00581.jpg" class="calibre596"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>This program displays the following output:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00582.jpg" class="calibre597"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>Although quite short, the preceding program illustrates several key points about exception handling. First, the code that you want to monitor for errors is contained within a <span class="bold1">try</span> block. Second, when an exception occurs (in this case, because of the attempt to index <span class="bold1">nums</span> beyond its bounds), the exception is thrown out of the <span class="bold1">try</span> block and caught by the <span class="bold1">catch</span> statement. At this point, control passes to the <span class="bold1">catch</span>, and the <span class="bold1">try</span> block is terminated. That is, <span class="bold1">catch</span> is <span class="italic">not</span> called. Rather, program execution is transferred to it. Thus, the <span class="bold1">println( )</span> statement following the out-of-bounds index will never execute. After the <span class="bold1">catch</span> statement executes, program control continues with the statements following the <span class="bold1">catch</span>. Thus, it is the job of your exception handler to remedy the problem that caused the exception so that program execution can continue normally.</span></div>
<div class="calibre23"><span>Remember, if no exception is thrown by a <span class="bold1">try</span> block, no <span class="bold1">catch</span> statements will be executed and program control resumes after the <span class="bold1">catch</span> statement. To confirm this, in the preceding program, change the line</span></div>
<div class="calibre1"><span><img alt="image" src="images/00583.jpg" class="calibre598"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>Now, no exception is generated, and the <span class="bold1">catch</span> block is not executed.</span></div>
<div class="calibre23"><span>It is important to understand that all code within a <span class="bold1">try</span> block is monitored for exceptions. This includes exceptions that might be generated by a method called from within the <span class="bold1">try</span> block. An exception thrown by a method called from within a <span class="bold1">try</span> block can be caught by the <span class="bold1">catch</span> statements associated with that <span class="bold1">try</span> block—assuming, of course, that the method did not catch the exception itself. For example, this is a valid program:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00584.jpg" class="calibre461"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>This program produces the following output, which is the same as that produced by the first version of the program shown earlier:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00585.jpg" class="calibre597"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>Since <span class="bold1">genException( )</span> is called from within a <span class="bold1">try</span> block, the exception that it generates (and does not catch) is caught by the <span class="bold1">catch</span> in <span class="bold1">main( )</span>. Understand, however, that if <span class="bold1">genException( )</span> had caught the exception itself, it never would have been passed back to <span class="bold1">main( )</span>.</span></div>
<div id="filepos779340" class="calibre1"><span class="calibre10"><span><span class="bold1">The Consequences of an Uncaught Exception</span></span></span></div>
<div class="calibre12"><span>Catching one of Java’s standard exceptions, as the preceding program does, has a side benefit: It prevents abnormal program termination. When an exception is thrown, it must be caught by some piece of code, somewhere. In general, if your program does not catch an exception, then it will be caught by the JVM. The trouble is that the JVM’s default exception handler terminates execution and displays a stack trace and error message. For example, in this version of the preceding example, the index out-of-bounds exception is not caught by the program.</span></div>
<div class="calibre1"><span><img alt="image" src="images/00586.jpg" class="calibre406"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>When the array index error occurs, execution is halted, and the following error message is displayed.</span></div>
<div class="calibre1"><span><img alt="image" src="images/00587.jpg" class="calibre599"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>While such a message is useful for you while debugging, it would not be something that you would want others to see, to say the least! This is why it is important for your program to handle exceptions itself, rather than rely upon the JVM.</span></div>
<div class="calibre23"><span>As mentioned earlier, the type of the exception must match the type specified in a <span class="bold1">catch</span> statement. If it doesn’t, the exception won’t be caught. For example, the following program tries to catch an array boundary error with a <span class="bold1">catch</span> statement for an <span class="bold1">ArithmeticException</span> (another of Java’s built-in exceptions). When the array boundary is overrun, an <span class="bold1">ArrayIndexOutOfBoundsException</span> is generated, but it won’t be caught by the <span class="bold1">catch</span> statement. This results in abnormal program termination.</span></div>
<div class="calibre1"><span><img alt="image" src="images/00588.jpg" class="calibre600"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>The output is shown here.</span></div>
<div class="calibre1"><span><img alt="image" src="images/00589.jpg" class="calibre601"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>As the output demonstrates, a <span class="bold1">catch</span> for <span class="bold1">ArithmeticException</span> won’t catch an <span class="bold1">ArrayIndexOutOfBoundsException</span>.</span></div>
<div id="filepos782057" class="calibre1"><span class="calibre10"><span><span class="bold1">Exceptions Enable You to Handle Errors Gracefully</span></span></span></div>
<div class="calibre12"><span>One of the key benefits of exception handling is that it enables your program to respond to an error and then continue running. For example, consider the following example that divides the elements of one array by the elements of another. If a division by zero occurs, an <span class="bold1">ArithmeticException</span> is generated. In the program, this exception is handled by reporting the error and then continuing with execution. Thus, attempting to divide by zero does not cause an abrupt run-time error resulting in the termination of the program. Instead, it is handled gracefully, allowing program execution to continue.</span></div>
<div class="calibre1"><span><img alt="image" src="images/00590.jpg" class="calibre602"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>The output from the program is shown here:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00591.jpg" class="calibre603"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>This example makes another important point: Once an exception has been handled, it is removed from the system. Therefore, in the program, each pass through the loop enters the <span class="bold1">try</span> block anew; any prior exceptions have been handled. This enables your program to handle repeated errors.</span></div>
<div id="filepos783620" class="calibre1"><span class="calibre10"><span><span class="bold1">Using Multiple catch Statements</span></span></span></div>
<div class="calibre12"><span>As stated earlier, you can associate more than one <span class="bold1">catch</span> statement with a <span class="bold1">try</span>. In fact, it is common to do so. However, each <span class="bold1">catch</span> must catch a different type of exception. For example, the program shown here catches both array boundary and divide-by-zero errors:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00592.jpg" class="calibre604"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>This program produces the following output:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00593.jpg" class="calibre605"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>As the output confirms, each <span class="bold1">catch</span> statement responds only to its own type of exception.</span></div>
<div class="calibre23"><span>In general, <span class="bold1">catch</span> expressions are checked in the order in which they occur in a program. Only a matching statement is executed. All other <span class="bold1">catch</span> blocks are ignored.</span></div>
<div id="filepos784896" class="calibre1"><span class="calibre10"><span><span class="bold1">Catching Subclass Exceptions</span></span></span></div>
<div class="calibre12"><span>There is one important point about multiple <span class="bold1">catch</span> statements that relates to subclasses. A <span class="bold1">catch</span> clause for a superclass will also match any of its subclasses. For example, since the superclass of all exceptions is <span class="bold1">Throwable</span>, to catch all possible exceptions, catch <span class="bold1">Throwable</span>. If you want to catch exceptions of both a superclass type and a subclass type, put the subclass first in the <span class="bold1">catch</span> sequence. If you don’t, then the superclass <span class="bold1">catch</span> will also catch all derived classes. This rule is self-enforcing because putting the superclass first causes unreachable code to be created, since the subclass <span class="bold1">catch</span> clause can never execute. In Java, unreachable code is an error.</span></div>
<div class="calibre23"><span>For example, consider the following program:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00594.jpg" class="calibre606"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>The output from the program is shown here:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00595.jpg" class="calibre605"/></span></div><div class="calibre11"> </div>
<div class="calibre29"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div>
<div class="calibre9"><span class="calibre10"><span><span class="bold1">Ask the Expert</span></span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">Q</span></span>:   Why would I want to catch superclass exceptions?</span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">A</span></span>:</span>   There are, of course, a variety of reasons. Here are a couple. First, if you add a <span class="bold1">catch</span> clause that catches exceptions of type <span class="bold1">Exception</span>, then you have effectively added a “catch all” clause to your exception handler that deals with all program-related exceptions. Such a “catch all” clause might be useful in a situation in which abnormal program termination must be avoided no matter what occurs. Second, in some situations, an entire category of exceptions can be handled by the same clause. Catching the superclass of these exceptions allows you to handle all without duplicated code.</span></div>
<div class="calibre36"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div><div class="calibre18"> </div>
<div class="calibre12"><span>In this case, <span class="bold1">catch(Throwable)</span> catches all exceptions except for <span class="bold1">ArrayIndexOutOfBounds</span>-<span class="bold1">Exception</span>. The issue of catching subclass exceptions becomes more important when you create exceptions of your own.</span></div>
<div id="filepos787955" class="calibre1"><span class="calibre10"><span><span class="bold1">Try Blocks Can Be Nested</span></span></span></div>
<div class="calibre12"><span>One <span class="bold1">try</span> block can be nested within another. An exception generated within the inner <span class="bold1">try</span> block that is not caught by a <span class="bold1">catch</span> associated with that <span class="bold1">try</span> is propagated to the outer <span class="bold1">try</span> block. For example, here the <span class="bold1">ArrayIndexOutOfBoundsException</span> is not caught by the inner <span class="bold1">catch</span>, but by the outer <span class="bold1">catch</span>:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00596.jpg" class="calibre607"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>The output from the program is shown here:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00597.jpg" class="calibre608"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>In this example, an exception that can be handled by the inner <span class="bold1">try</span>—in this case, a divide-by-zero error—allows the program to continue. However, an array boundary error is caught by the outer <span class="bold1">try</span>, which causes the program to terminate.</span></div>
<div class="calibre23"><span>Although certainly not the only reason for nested <span class="bold1">try</span> statements, the preceding program makes an important point that can be generalized. Often nested <span class="bold1">try</span> blocks are used to allow different categories of errors to be handled in different ways. Some types of errors are catastrophic and cannot be fixed. Some are minor and can be handled immediately. You might use an outer <span class="bold1">try</span> block to catch the most severe errors, allowing inner <span class="bold1">try</span> blocks to handle less serious ones.</span></div>
<div id="filepos789793" class="calibre1"><span class="calibre10"><span><span class="bold1">Throwing an Exception</span></span></span></div>
<div class="calibre12"><span>The preceding examples have been catching exceptions generated automatically by the JVM. However, it is possible to manually throw an exception by using the <span class="bold1">throw</span> statement. Its general form is shown here:</span></div>
<div class="calibre27"><span>throw <span class="italic">exceptOb</span>;</span></div>
<div class="calibre27"><span>Here, <span class="italic">exceptOb</span> must be an object of an exception class derived from <span class="bold1">Throwable</span>.</span></div>
<div class="calibre23"><span>Here is an example that illustrates the <span class="bold1">throw</span> statement by manually throwing an <span class="bold1">ArithmeticException</span>:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00598.jpg" class="calibre609"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>The output from the program is shown here:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00599.jpg" class="calibre610"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>Notice how the <span class="bold1">ArithmeticException</span> was created using <span class="bold1">new</span> in the <span class="bold1">throw</span> statement. Remember, <span class="bold1">throw</span> throws an object. Thus, you must create an object for it to throw. That is, you can’t just throw a type.</span></div>
<div id="filepos791301" class="calibre1"><span class="calibre10"><span><span class="bold1">Rethrowing an Exception</span></span></span></div>
<div class="calibre12"><span>An exception caught by one <span class="bold1">catch</span> statement can be rethrown so that it can be caught by an outer <span class="bold1">catch</span>. The most likely reason for rethrowing this way is to allow multiple handlers access to the exception. For example, perhaps one exception handler manages one aspect of an exception, and a second handler copes with another aspect. Remember, when you rethrow an exception, it will not be recaught by the same <span class="bold1">catch</span> statement. It will propagate to the next <span class="bold1">catch</span> statement. The following program illustrates rethrowing an exception:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00600.jpg" class="calibre611"/></span></div><div class="calibre11"> </div>
<div class="calibre29"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div>
<div class="calibre9"><span class="calibre10"><span><span class="bold1">Ask the Expert</span></span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">Q</span></span>:   Why would I want to manually throw an exception?</span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">A</span></span>:</span>   Most often, the exceptions that you will throw will be instances of exception classes that you created. As you will see later in this chapter, creating your own exception classes allows you to handle errors in your code as part of your program’s overall exception handling strategy.</span></div>
<div class="calibre36"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div><div class="calibre18"> </div>
<div class="calibre1"><span><img alt="image" src="images/00601.jpg" class="calibre612"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>In this program, divide-by-zero errors are handled locally, by <span class="bold1">genException( )</span>, but an array boundary error is rethrown. In this case, it is caught by <span class="bold1">main( )</span>.</span></div>
<div id="filepos793585" class="calibre1"><span class="calibre10"><span><span class="bold1">A Closer Look at Throwable</span></span></span></div>
<div class="calibre12"><span>Up to this point, we have been catching exceptions, but we haven’t been doing anything with the exception object itself. As the preceding examples all show, a <span class="bold1">catch</span> clause specifies an exception type and a parameter. The parameter receives the exception object. Since all exceptions are subclasses of <span class="bold1">Throwable</span>, all exceptions support the methods defined by <span class="bold1">Throwable</span>. Several commonly used ones are shown in <a href="#filepos794257">Table 9-1</a>.</span></div>
<div class="calibre28">
<div id="filepos794257" class="calibre44"><span><img alt="image" src="images/00602.jpg" class="calibre613"/></span></div>
<div class="calibre9"><span><img alt="image" src="images/00057.jpg" class="calibre34"/></span></div>
<div class="calibre9"><span><span class="bold1">Table 9-1</span>   Commonly Used Methods Defined by <span class="bold1">Throwable</span></span></div><div class="calibre18"> </div>
</div>
<div class="calibre23"><span>Of the methods defined by <span class="bold1">Throwable</span>, two of the most interesting are <span class="bold1">printStackTrace( )</span> and <span class="bold1">toString( )</span>. You can display the standard error message plus a record of the method calls that lead up to the exception by calling <span class="bold1">printStackTrace( )</span>. You can use <span class="bold1">toString( )</span> to retrieve the standard error message. The <span class="bold1">toString( )</span> method is also called when an exception is used as an argument to <span class="bold1">println( )</span>. The following program demonstrates these methods:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00603.jpg" class="calibre614"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>The output from this program is shown here:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00604.jpg" class="calibre615"/></span></div><div class="calibre11"> </div>
<div id="filepos795646" class="calibre1"><span class="calibre10"><span><span class="bold1">Using finally</span></span></span></div>
<div class="calibre12"><span>Sometimes you will want to define a block of code that will execute when a <span class="bold1">try/catch</span> block is left. For example, an exception might cause an error that terminates the current method, causing its premature return. However, that method may have opened a file or a network connection that needs to be closed. Such types of circumstances are common in programming, and Java provides a convenient way to handle them: <span class="bold1">finally</span>.</span></div>
<div class="calibre23"><span>To specify a block of code to execute when a <span class="bold1">try/catch</span> block is exited, include a <span class="bold1">finally</span> block at the end of a <span class="bold1">try</span>/<span class="bold1">catch</span> sequence. The general form of a <span class="bold1">try</span>/<span class="bold1">catch</span> that includes <span class="bold1">finally</span> is shown here.</span></div>
<div class="calibre1"><span><img alt="image" src="images/00605.jpg" class="calibre616"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>The <span class="bold1">finally</span> block will be executed whenever execution leaves a <span class="bold1">try/catch</span> block, no matter what conditions cause it. That is, whether the <span class="bold1">try</span> block ends normally, or because of an exception, the last code executed is that defined by <span class="bold1">finally</span>. The <span class="bold1">finally</span> block is also executed if any code within the <span class="bold1">try</span> block or any of its <span class="bold1">catch</span> statements return from the method.</span></div>
<div class="calibre23"><span>Here is an example of <span class="bold1">finally</span>:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00606.jpg" class="calibre617"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>Here is the output produced by the program:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00607.jpg" class="calibre618"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>As the output shows, no matter how the <span class="bold1">try</span> block is exited, the <span class="bold1">finally</span> block is executed.</span></div>
<div id="filepos797855" class="calibre1"><span class="calibre10"><span><span class="bold1">Using throws</span></span></span></div>
<div class="calibre12"><span>In some cases, if a method generates an exception that it does not handle, it must declare that exception in a <span class="bold1">throws</span> clause. Here is the general form of a method that includes a <span class="bold1">throws</span> clause:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00608.jpg" class="calibre619"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>Here, <span class="italic">except-list</span> is a comma-separated list of exceptions that the method might throw outside of itself.</span></div>
<div class="calibre23"><span>You might be wondering why you did not need to specify a <span class="bold1">throws</span> clause for some of the preceding examples, which threw exceptions outside of methods. The answer is that exceptions that are subclasses of <span class="bold1">Error</span> or <span class="bold1">RuntimeException</span> don’t need to be specified in a <span class="bold1">throws</span> list. Java simply assumes that a method may throw one. All other types of exceptions <span class="italic">do</span> need to be declared. Failure to do so causes a compile-time error.</span></div>
<div class="calibre23"><span>Actually, you saw an example of a <span class="bold1">throws</span> clause earlier in this book. As you will recall, when performing keyboard input, you needed to add the clause</span></div>
<div class="calibre1"><span><img alt="image" src="images/00609.jpg" class="calibre620"/></span></div><div class="calibre11"> </div>
<div class="calibre27"><span>to <span class="bold1">main( )</span>. Now you can understand why. An input statement might generate an <span class="bold1">IOException</span>, and at that time, we weren’t able to handle that exception. Thus, such an exception would be thrown out of <span class="bold1">main( )</span> and needed to be specified as such. Now that you know about exceptions, you can easily handle <span class="bold1">IOException</span>.</span></div>
<div class="calibre23"><span>Let’s look at an example that handles <span class="bold1">IOException</span>. It creates a method called <span class="bold1">prompt( )</span>, which displays a prompting message and then reads a character from the keyboard. Since input is being performed, an <span class="bold1">IOException</span> might occur. However, the <span class="bold1">prompt( )</span> method does not handle <span class="bold1">IOException</span> itself. Instead, it uses a <span class="bold1">throws</span> clause, which means that the calling method must handle it. In this example, the calling method is <span class="bold1">main( )</span>, and it deals with the error.</span></div>
<div class="calibre1"><span><img alt="image" src="images/00610.jpg" class="calibre621"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>On a related point, notice that <span class="bold1">IOException</span> is fully qualified by its package name <span class="bold1">java.io</span>. As you will learn in <a href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_017.html#filepos823752">Chapter 10</a>, Java’s I/O system is contained in the <span class="bold1">java.io</span> package. Thus, the <span class="bold1">IOException</span> is also contained there. It would also have been possible to import <span class="bold1">java.io</span> and then refer to <span class="bold1">IOException</span> directly.</span></div>
<div id="filepos801048" class="calibre1"><span class="calibre10"><span><span class="bold1">Three Recently Added Exception Features</span></span></span></div>
<div class="calibre12"><span>Beginning with JDK 7, Java's exception handling mechanism has been expanded with the addition of three features. The first supports <span class="italic">automatic resource management</span>, which automates the process of releasing a resource, such as a file, when it is no longer needed. It is based on an expanded form of <span class="bold1">try</span>, called the <span class="bold1"><span class="italic">try</span></span><span class="italic">-with-resources</span> statement, and it is described in <a href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_017.html#filepos823752">Chapter 10</a>, when files are discussed. The second new feature is called <span class="italic">multi-catch</span>, and the third is sometimes called <span class="italic">final rethrow</span> or <span class="italic">more precise rethrow</span>. These two features are described here.</span></div>
<div class="calibre23"><span>Multi-catch allows two or more exceptions to be caught by the same <span class="bold1">catch</span> clause. As you learned earlier, it is possible (indeed, common) for a <span class="bold1">try</span> to be followed by two or more <span class="bold1">catch</span> clauses. Although each <span class="bold1">catch</span> clause often supplies its own unique code sequence, it is not uncommon to have situations in which two or more <span class="bold1">catch</span> clauses execute <span class="italic">the same code sequence</span> even though they catch different exceptions. Instead of having to catch each exception type individually, you can now use a single <span class="bold1">catch</span> clause to handle the exceptions without code duplication.</span></div>
<div class="calibre23"><span>To create a multi-catch, specify a list of exceptions within a single <span class="bold1">catch</span> clause. You do this by separating each exception type in the list with the OR operator. Each multi-catch parameter is implicitly <span class="bold1">final</span>. (You can explicitly specify <span class="bold1">final</span>, if desired, but it is not necessary.) Because each multi-catch parameter is implicitly <span class="bold1">final</span>, it can't be assigned a new value.</span></div>
<div class="calibre23"><span>Here is how you can use the multi-catch feature to catch both <span class="bold1">ArithmeticException</span> and <span class="bold1">ArrayIndexOutOfBoundsException</span> with a single <span class="bold1">catch</span> clause:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00611.jpg" class="calibre82"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>Here is a simple program that demonstrates the use of this multi-catch:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00612.jpg" class="calibre622"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>The program will generate an <span class="bold1">ArithmeticException</span> when the division by zero is attempted. It will generate an <span class="bold1">ArrayIndexOutOfBoundsException</span> when the attempt is made to access outside the bounds of <span class="bold1">chrs</span>. Both exceptions are caught by the single <span class="bold1">catch</span> statement.</span></div>
<div class="calibre23"><span>The more precise rethrow feature restricts the type of exceptions that can be rethrown to only those checked exceptions that the associated <span class="bold1">try</span> block throws, that are not handled by a preceding <span class="bold1">catch</span> clause, and that are a subtype or supertype of the parameter. While this capability might not be needed often, it is now available for use. For the final rethrow feature to be in force, the <span class="bold1">catch</span> parameter must be effectively <span class="bold1">final</span>. This means that it must not be assigned a new value inside the <span class="bold1">catch</span> block. It can also be explicitly specified as <span class="bold1">final</span>, but this is not necessary.</span></div>
<div id="filepos804759" class="calibre1"><span class="calibre10"><span><span class="bold1">Java’s Built-in Exceptions</span></span></span></div>
<div class="calibre12"><span>Inside the standard package <span class="bold1">java.lang</span>, Java defines several exception classes. A few have been used by the preceding examples. The most general of these exceptions are subclasses of the standard type <span class="bold1">RuntimeException</span>. Since <span class="bold1">java.lang</span> is implicitly imported into all Java programs, most exceptions derived from <span class="bold1">RuntimeException</span> are automatically available. Furthermore, they need not be included in any method’s <span class="bold1">throws</span> list. In the language of Java, these are called <span class="italic">unchecked exceptions</span> because the compiler does not check to see if a method handles or throws these exceptions. The unchecked exceptions defined in <span class="bold1">java.lang</span> are listed in <a href="#filepos806147">Table 9-2</a>. <a href="#filepos806585">Table 9-3</a> lists those exceptions defined by <span class="bold1">java.lang</span> that must be included in a method’s <span class="bold1">throws</span> list if that method can generate one of these exceptions and does not handle it itself. These are called <span class="italic">checked exceptions</span>. In addition to the exceptions in <span class="bold1">java.lang</span>, Java defines several other types of exceptions that relate to other packages, such as <span class="bold1">IOException</span> mentioned earlier.</span></div>
<div class="calibre28">
<div id="filepos806147" class="calibre44"><span><img alt="image" src="images/00613.jpg" class="calibre623"/></span></div>
<div class="calibre9"><span><img alt="image" src="images/00057.jpg" class="calibre34"/></span></div>
<div class="calibre9"><span><span class="bold1">Table 9-2</span>   The Unchecked Exceptions Defined in <span class="bold1">java.lang</span></span></div><div class="calibre18"> </div>
</div>
<div class="calibre28">
<div id="filepos806585" class="calibre44"><span><img alt="image" src="images/00614.jpg" class="calibre406"/></span></div>
<div class="calibre9"><span><img alt="image" src="images/00057.jpg" class="calibre34"/></span></div>
<div class="calibre9"><span><span class="bold1">Table 9-3</span>   The Checked Exceptions Defined in <span class="bold1">java.lang</span></span></div><div class="calibre18"> </div>
</div>
<div class="calibre35"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div>
<div class="calibre9"><span class="calibre10"><span><span class="bold1">Ask the Expert</span></span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">Q</span></span>:   I have heard that Java supports something called <span class="italic">chained exceptions</span></span>. <span class="bold1">What are they?</span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">A</span></span>:</span>   Chained exceptions were added to Java by JDK 1.4. The chained exception feature allows you to specify one exception as the underlying cause of another. For example, imagine a situation in which a method throws an <span class="bold1">ArithmeticException</span> because of an attempt to divide by zero. However, the actual cause of the problem was that an I/O error occurred, which caused the divisor to be set improperly. Although the method must certainly throw an <span class="bold1">ArithmeticException</span>, since that is the error that occurred, you might also want to let the calling code know that the underlying cause was an I/O error. Chained exceptions let you handle this, and any other situation, in which layers of exceptions exist.</span></div>
<div class="calibre624"><span>To allow chained exceptions, two constructors and two methods were added to <span class="bold1">Throwable</span>. The constructors are shown here:</span></div>
<div class="calibre1"><span>Throwable(Throwable <span class="italic">causeExc</span>)</span></div>
<div class="calibre9"><span>Throwable(String <span class="italic">msg</span>, Throwable <span class="italic">causeExc</span>)</span></div>
<div class="calibre1"><span>In the first form, <span class="italic">causeExc</span> is the exception that causes the current exception. That is, <span class="italic">causeExc</span> is the underlying reason that an exception occurred. The second form allows you to specify a description at the same time that you specify a cause exception. These two constructors have also been added to the <span class="bold1">Error</span>, <span class="bold1">Exception</span>, and <span class="bold1">RuntimeException</span> classes.</span></div>
<div class="calibre624"><span>The chained exception methods added to <span class="bold1">Throwable</span> are <span class="bold1">getCause( )</span> and <span class="bold1">initCause( )</span>. These methods are shown here:</span></div>
<div class="calibre1"><span>Throwable getCause( )</span></div>
<div class="calibre9"><span>Throwable initCause(Throwable <span class="italic">causeExc</span>)</span></div>
<div class="calibre1"><span>The <span class="bold1">getCause( )</span> method returns the exception that underlies the current exception. If there is no underlying exception, <span class="bold1">null</span> is returned. The <span class="bold1">initCause( )</span> method associates <span class="italic">causeExc</span> with the invoking exception and returns a reference to the exception. Thus, you can associate a cause with an exception after the exception has been created. In general, <span class="bold1">initCause( )</span> is used to set a cause for legacy exception classes that don’t support the two additional constructors described earlier.</span></div>
<div class="calibre624"><span>Chained exceptions are not something that every program will need. However, in cases in which knowledge of an underlying cause is useful, they offer an elegant solution.</span></div>
<div class="calibre36"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div><div class="calibre18"> </div>
<div id="filepos810713" class="calibre9"><span class="calibre10"><span><span class="bold1">Creating Exception Subclasses</span></span></span></div>
<div class="calibre12"><span>Although Java’s built-in exceptions handle most common errors, Java’s exception handling mechanism is not limited to these errors. In fact, part of the power of Java’s approach to exceptions is its ability to handle exception types that you create. Through the use of custom exceptions, you can manage errors that relate specifically to your application. Creating an exception class is easy. Just define a subclass of <span class="bold1">Exception</span> (which is, of course, a subclass of <span class="bold1">Throwable</span>). Your subclasses don’t need to actually implement anything—it is their existence in the type system that allows you to use them as exceptions.</span></div>
<div class="calibre23"><span>The <span class="bold1">Exception</span> class does not define any methods of its own. It does, of course, inherit those methods provided by <span class="bold1">Throwable</span>. Thus, all exceptions, including those that you create, have the methods defined by <span class="bold1">Throwable</span> available to them. Of course, you can override one or more of these methods in exception subclasses that you create.</span></div>
<div class="calibre23"><span>Here is an example that creates an exception called <span class="bold1">NonIntResultException</span>, which is generated when the result of dividing two integer values produces a result with a fractional component. <span class="bold1">NonIntResultException</span> has two fields which hold the integer values; a constructor; and an override of the <span class="bold1">toString( )</span> method, allowing the description of the exception to be displayed using <span class="bold1">println( )</span>.</span></div>
<div class="calibre1"><span><img alt="image" src="images/00615.jpg" class="calibre625"/></span></div><div class="calibre11"> </div>
<div class="calibre23"><span>The output from the program is shown here:</span></div>
<div class="calibre1"><span><img alt="image" src="images/00616.jpg" class="calibre626"/></span></div><div class="calibre11"> </div>
<div class="calibre29"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div>
<div class="calibre9"><span class="calibre10"><span><span class="bold1">Ask the Expert</span></span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">Q</span></span>:   When should I use exception handling in a program? When should I create my own custom exception classes?</span></span></div>
<div class="calibre19"><span><span class="bold1"><span><span class="calibre10">A</span></span>:</span>   Since the Java API makes extensive use of exceptions to report errors, nearly all real-world programs will make use of exception handling. This is the part of exception handling that most new Java programmers find easy. It is harder to decide when and how to use your own custom-made exceptions. In general, errors can be reported in two ways: return values and exceptions. When is one approach better than the other? Simply put, in Java, exception handling should be the norm. Certainly, returning an error code is a valid alternative in some cases, but exceptions provide a more powerful, structured way to handle errors. They are the way professional Java programmers handle errors in their code.</span></div>
<div class="calibre36"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div><div class="calibre18"> </div>
<div class="calibre11"> </div><table cellspacing="0" cellpadding="0" class="calibre37">
<colgroup class="calibre38">
<col class="calibre72"/>
<col class="calibre73"/>
</colgroup>
<tr class="calibre41">
<td valign="top" id="filepos814531" class="calibre74"><span class="calibre10"><span class="bold1">Try This 9-1</span> </span></td>
<td valign="top" class="calibre75"><span class="calibre10">Adding Exceptions to the Queue Class</span></td>
</tr></table><div class="calibre43"> </div>
<div class="calibre1"><span><img alt="image" src="images/00617.jpg" class="calibre627"/></span></div><div class="calibre11"> </div>
<div class="calibre12"><span>In this project, you will create two exception classes that can be used by the queue classes developed by Project 8-1. They will indicate the queue-full and queue-empty error conditions. These exceptions can be thrown by the <span class="bold1">put( )</span> and <span class="bold1">get( )</span> methods, respectively. For the sake of simplicity, this project will add these exceptions to the <span class="bold1">FixedQueue</span> class, but you can easily incorporate them into the other queue classes from Project 8-1.</span></div>
<div class="calibre19"><span>  <span class="bold1">1</span>.  You will create two files that will hold the queue exception classes. Call the first file <span class="bold1">QueueFullException.java</span> and enter into it the following:</span></div>
<div class="calibre47"><span>        <img alt="image" src="images/00618.jpg" class="calibre628"/></span></div>
<div class="calibre47"><span>        A <span class="bold1">QueueFullException</span> will be generated when an attempt is made to store an item in an already full queue.</span></div>
<div class="calibre47"><span>  <span class="bold1">2</span>.  Create the second file <span class="bold1">QueueEmptyException.java</span> and enter into it the following:</span></div>
<div class="calibre47"><span>        <img alt="image" src="images/00619.jpg" class="calibre629"/></span></div>
<div class="calibre47"><span>        A <span class="bold1">QueueEmptyException</span> will be generated when an attempt is made to remove an element from an empty queue.</span></div>
<div class="calibre47"><span>  <span class="bold1">3</span>.  Modify the <span class="bold1">FixedQueue</span> class so that it throws exceptions when an error occurs, as shown here. Put it in a file called <span class="bold1">FixedQueue.java</span>.</span></div>
<div class="calibre47"><span>        <img alt="image" src="images/00620.jpg" class="calibre630"/></span></div>
<div class="calibre47"><span>        Notice that two steps are required to add exceptions to <span class="bold1">FixedQueue</span>. First, <span class="bold1">get( )</span> and <span class="bold1">put( )</span> must have a <span class="bold1">throws</span> clause added to their declarations. Second, when an error occurs, these methods throw an exception. Using exceptions allows the calling code to handle the error in a rational fashion. You might recall that the previous versions simply reported the error. Throwing an exception is a much better approach.</span></div>
<div class="calibre47"><span>  <span class="bold1">4</span>.  To try the updated <span class="bold1">FixedQueue</span> class, use the <span class="bold1">QExcDemo</span> class shown here. Put it into a file called <span class="bold1">QExcDemo.java</span>:</span></div>
<div class="calibre47"><span>        <img alt="image" src="images/00621.jpg" class="calibre631"/></span></div>
<div class="calibre47"><span>  <span class="bold1">5</span>.  Since <span class="bold1">FixedQueue</span> implements the <span class="bold1">ICharQ</span> interface, which defines the two queue methods <span class="bold1">get( )</span> and <span class="bold1">put( )</span>, <span class="bold1">ICharQ</span> will need to be changed to reflect the <span class="bold1">throws</span> clause. Here is the updated <span class="bold1">ICharQ</span> interface. Remember, this must be in a file by itself called <span class="bold1">ICharQ.java</span>.</span></div>
<div class="calibre47"><span>        <img alt="image" src="images/00622.jpg" class="calibre632"/></span></div>
<div class="calibre47"><span>  <span class="bold1">6</span>.  Now, compile the updated <span class="bold1">ICharQ.java</span> file. Then, compile <span class="bold1">FixedQueue.java</span>, <span class="bold1">QueueFullException.java</span>, <span class="bold1">QueueEmptyException.java</span>, and <span class="bold1">QExcDemo.java</span>. Finally, run <span class="bold1">QExcDemo</span>. You will see the following output:</span></div>
<div class="calibre47"><span>        <img alt="image" src="images/00623.jpg" class="calibre633"/></span></div>
<div class="calibre36"><span><img alt="image" src="images/00005.jpg" class="calibre34"/></span></div><div class="calibre18"> </div>
<div id="filepos819837" class="calibre1"><span class="calibre10"><span><img alt="image" src="images/00059.jpg" class="calibre104"/>   <span class="bold1"><span class="italic">Chapter 9 Self Test</span></span></span></span></div><div class="calibre11"> </div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos820117" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1540646">1</a></span>.  What class is at the top of the exception hierarchy?</span></div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos820337" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1541021">2</a></span>.  Briefly explain how to use <span class="bold1">try</span> and <span class="bold1">catch</span>.</span></div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos820560" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1541541">3</a></span>.  What is wrong with this fragment?</span></div>
<div class="calibre31"><blockquote class="calibre66"><span><img alt="image" src="images/00624.jpg" class="calibre634"/></span></blockquote></div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos820919" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1542063">4</a></span>.  What happens if an exception is not caught?</span></div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos821130" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1542439">5</a></span>.  What is wrong with this fragment?</span></div>
<div class="calibre31"><blockquote class="calibre66"><span><img alt="image" src="images/00625.jpg" class="calibre635"/></span></blockquote></div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos821489" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1543065">6</a></span>.  Can an inner <span class="bold1">catch</span> rethrow an exception to an outer <span class="bold1">catch</span>?</span></div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos821729" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1543436">7</a></span>.  The <span class="bold1">finally</span> block is the last bit of code executed before your program ends. True or False? Explain your answer.</span></div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos822016" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1543902">8</a></span>.  What type of exceptions must be explicitly declared in a <span class="bold1">throws</span> clause of a method?</span></div>
<div class="calibre47"><span>  <span class="bold1"><a id="filepos822274" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1544377">9</a></span>.  What is wrong with this fragment?</span></div>
<div class="calibre31"><blockquote class="calibre66"><span><img alt="image" src="images/00626.jpg" class="calibre636"/></span></blockquote></div>
<div class="calibre47"><span><span class="bold1"><a id="filepos822616" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1544931">10</a></span>.  In question 3 of the <a href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_013.html#filepos547570">Chapter 6</a> Self Test, you created a <span class="bold1">Stack</span> class. Add custom exceptions to your class that report stack full and stack empty conditions.</span></div>
<div class="calibre47"><span><span class="bold1"><a id="filepos822959" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1545746">11</a></span>.  What are the three ways that an exception can be generated?</span></div>
<div class="calibre47"><span><span class="bold1"><a id="filepos823172" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1546182">12</a></span>.  What are the two direct subclasses of <span class="bold1">Throwable</span>?</span></div>
<div class="calibre47"><span><span class="bold1"><a id="filepos823381" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1546521">13</a></span>.  What is the multi-catch feature?</span></div>
<div class="calibre47"><span><span class="bold1"><a id="filepos823567" href="CR%21CDS4MRPTP172DC9AQDQQBWENKH9V_split_025.html#filepos1546891">14</a></span>.  Should your code typically catch exceptions of type <span class="bold1">Error</span>?</span></div>  <div class="mbppagebreak" id="calibre_pb_16"></div>
</body></html>
